parameters:
#    attachmentgenie_example.example.class: Attachmentgenie\ExampleBundle\Example

services:
#    attachmentgenie_example.example:
#        class: %attachmentgenie_example.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
