parameters:
#    attachmentgenie_example_backend.example.class: Attachmentgenie\ExampleBackendBundle\Example

services:
#    attachmentgenie_example_backend.example:
#        class: %attachmentgenie_example_backend.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
